update script

diff --git a/picom-manager b/picom-manager
--- a/picom-manager
+++ b/picom-manager
@@ -89,6 +89,10 @@ run_compositor() {
                 check_configs ;;
             blur)
                 check_configs ;;
+            custom)
+                ;;
+            *)
+                echo "-m - Invalid compositor mode";;
         esac
     else
             echo "$CONFIG_DIR was not found, falling back to default picom configuration."
@@ -114,6 +118,13 @@ OPTIONS:
     -t                       Toggle the compositor."
 }
 
+if [ "$#" -eq 0 ]
+then
+    help >&2
+    exit 1
+fi
+
+
 while getopts "c:df:hm:r:t" opt; do
     case $opt in
         c) PICOM_CONFIG="$OPTARG"; COMPOSITOR_MODE="custom";;
@@ -128,8 +139,4 @@ done
 shift $((OPTIND - 1))
 
 # If there is no argument, show help.
-if [ "$#" -eq 0 ]
-then
-    help >&2
-    exit 1
-fi
+
